### ISSUE TITLE
fix acreage pct calc

### ISSUE THREAD

**Issue by clayton-aldern** [Grist-Data-Desk/STLoR#16]
@parkerziegler I think [this line](https://github.com/Grist-Data-Desk/STLoR/blob/f33f39f871f48192c58aebad561726d93b590368/interactives/stlors-map/src/lib/components/AcreagePanel.svelte#L11C19-L11C66) should be `$: pctCoverage = (stats.stl_total_acres / stats.acres * 2) * 100;` (i.e. move the 2 inside the parentheses)?

**Comment by parkerziegler** [comment]
Good read that the calculation is off! Looking a bit closer, I think it should actually be:

```js
$: pctCoverage = stats.stl_total_acres / (stats.acres * 2) * 100;
```

which Prettier will rewrite to:

```js
$: pctCoverage = (stats.stl_total_acres / (stats.acres * 2)) * 100;
```

to try to disambiguate operator order (which, I absolutely needed on this one). As a quick sanity check, I punched the following into Node:

```sh
node
Welcome to Node.js v20.12.2.
Type ".help" for more information.
> // Original implementation.
undefined
> (294895.97 / 823718.64) * 2 * 100
71.60114040881726
> // Attempted fix.
undefined
> (294895.97 / 823718.64 * 2) * 100
71.60114040881726
> // Final fix.
undefined
> (294895.97 / (823718.64 * 2)) * 100
17.9002
```

The last agrees with the numbers you sent in Slack, so I'll push a commit with that change in real quick! Thanks for catching this eagle eyes 🙏
